name: .NET Framework Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework builds

    steps:
    - uses: actions/checkout@v4
    - name: Check installed .NET SDKs
      run: dotnet --list-sdks
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
